version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management  # Includes RabbitMQ with the management plugin
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port (used by applications)
      - "15672:15672" # Management UI port (used for web interface)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent storage

volumes:
  rabbitmq_data:
